BATCH_SIZE = 64
SEQ_LENGTH = 60    

TEST_SEQ_LENGTH = 120   
MAX_LEN = 2 * TEST_SEQ_LENGTH + 1

HIDDEN_DIM = 64
STACK_DEPTH = SEQ_LENGTH
LEARNING_RATE = 1e-4
STEPS = 6000
EVAL_FREQ = 100

# input
VOCAB_PAD, VOCAB_0, VOCAB_1, VOCAB_EQ, VOCAB_EOS = 0, 1, 2, 3, 4
VOCAB_SIZE = 5

# stack
STACK_NULL, STACK_0, STACK_1 = 0, 1, 2
STACK_VOCAB_SIZE = 3

# memory actions
ACT_NOOP, ACT_PUSH_0, ACT_PUSH_1, ACT_POP = 0, 1, 2, 3
NUM_MEM_ACTIONS = 4

# buffer
OUT_NOOP, OUT_EMIT_0, OUT_EMIT_1, OUT_EMIT_EOS = 0, 1, 2, 3
NUM_BUF_ACTIONS = 4

#controller states
STATE_READ = 0
STATE_WRITE = 1
NUM_STATES = 2